name: magicando
favicon: null
layout_spectrum: 0.7205393745098263
typography_spectrum: 0.33478361926972866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24254570063203573
  lightness: 0.060407147044315934
  saturation: 0.975728199351579
  rhythmicContrast: 0.3071066902484745
purpose: []
